
gestor_fct_homepage:
    path:     /
    defaults: { _controller: GestorFCTBundle:Default:index }    

Empresas_all:
    path:     /empresas/all
    defaults: { _controller: GestorFCTBundle:Empresas:all }

Empresas_new:
    path:     /empresas/new
    defaults: { _controller: GestorFCTBundle:Empresas:new }

Empresas_delete:
    path:     /empresas/delete/{id}
    defaults: { _controller: GestorFCTBundle:Empresas:delete }

Empresas_update:
    path:     /empresas/update/{id}
    defaults: { _controller: GestorFCTBundle:Empresas:update }

Alumnos_all:
    path:     /alumnos/all
    defaults: { _controller: GestorFCTBundle:Alumnos:all }

Alumnos_new:
    path:     /alumnos/new
    defaults: { _controller: GestorFCTBundle:Alumnos:new }

Alumnos_delete:
    path:     /alumnos/delete/{id}
    defaults: { _controller: GestorFCTBundle:Alumnos:delete }

Alumnos_update:
    path:     /alumnos/update/{id}
    defaults: { _controller: GestorFCTBundle:Alumnos:update }

Profesores_all:
    path:     /profesores/all
    defaults: { _controller: GestorFCTBundle:Profesores:all }

Profesores_new:
    path:     /profesores/new
    defaults: { _controller: GestorFCTBundle:Profesores:new }

Profesores_delete:
    path:     /profesores/delete/{id}
    defaults: { _controller: GestorFCTBundle:Profesores:delete }

Profesores_update:
    path:     /profesores/update/{id}
    defaults: { _controller: GestorFCTBundle:Profesores:update }

Grupo_all:
    path:     /grupo/all
    defaults: { _controller: GestorFCTBundle:Grupo:all }

Grupo_new:
    path:     /grupo/new
    defaults: { _controller: GestorFCTBundle:Grupo:new }

Grupo_delete:
    path:     /grupo/delete/{id}
    defaults: { _controller: GestorFCTBundle:Grupo:delete }

Grupo_update:
    path:     /grupo/update/{id}
    defaults: { _controller: GestorFCTBundle:Grupo:update }

Asignaciones_all:
    path:     /asignaciones/all
    defaults: { _controller: GestorFCTBundle:Asignaciones:all }

Asignaciones_new:
    path:     /asignaciones/new
    defaults: { _controller: GestorFCTBundle:Asignaciones:new }

Asignaciones_delete:
    path:     /asignaciones/delete/{id}
    defaults: { _controller: GestorFCTBundle:Asignaciones:delete }

Asignaciones_update:
    path:     /Asignaciones/update/{id}
    defaults: { _controller: GestorFCTBundle:Asignaciones:update }
