<?php

namespace GestorFCTBundle\Repository;

/**
 * AsignacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
